INSERT INTO RECIPE (ID, DESCRIPTION, IMG, INGREDIENTS, NAME, RATING, RATINGS) VALUES (1, 'Bake potatoes 1 hour in a 200 C / Gas 6 oven. Scoop out the inside of the potatoes and set aside. Reserve the skins for another recipe or discard.', 'http://www.reciperoulette.tv/public/upload/415771f02f705091f991b537f5924d9c.jpg', '4 baking potatoes, 150g butter, 85g plain flour, 1.5 litres milk, 100g spring onions, chopped, 3/4 teaspoon salt, 1/2 teaspoon ground black pepper, 12 rashers streaky bacon, cooked and crumbled, 150g Cheddar cheese, grated, 225ml soured cream', 'Cheese and bacon potato soup', 3, '3');
INSERT INTO RECIPE (ID, DESCRIPTION, IMG, INGREDIENTS, NAME, RATING, RATINGS) VALUES (2, 'Mix all together and put into a casserole dish.', 'http://www.reciperoulette.tv/public/assets/images/food.jpg', '2 carrots, sliced, 1 tin corned beef, 100g frozen garden peas, or 1 tin peas, Worcestershire sause or barbecue sauce, salt and pepper to taste, 250 to 400g mashed potato, 1 to 2 handfuls grated cheese', 'Cornbeef pie', 4, '4');
INSERT INTO RECIPE (ID, DESCRIPTION, IMG, INGREDIENTS, NAME, RATING, RATINGS) VALUES (3, 'Cook the carrots in the microwave or in a pan of boiling water until tender. Drain and combine with the corned beef, peas, Worcestershire sauce or barbecue sauce, salt and pepper. Mix all together and put into a casserole dish.', 'http://www.reciperoulette.tv/public/upload/38f6bcabd40371197671883e75f2ad96.jpg', '2 carrots, sliced, 1 tin corned beef, 100g frozen garden peas, or 1 tin peas, Worcestershire sause or barbecue sauce, salt and pepper to taste, 250 to 400g mashed potato, 1 to 2 handfuls grated cheese, 75g butter, 550g sifted icing sugar', 'Turkey meatloaf', 1, '1');
INSERT INTO RECIPE (ID, DESCRIPTION, IMG, INGREDIENTS, NAME, RATING, RATINGS) VALUES (4, 'In a large bowl cream butter and cheese. Stir in flour and salt; mix well. On a lightly floured surface, roll the dough out to 1.25cm in thickness. Cut into 5cm strips and sprinkle with chilli powder, if desired.', 'http://www.reciperoulette.tv/public/upload/4d51ad0a5edb6afa46fc393fb2a1af48.jpg', '120g butter, 450g grated Cheddar cheese, 250g plain flour, 1 teaspoon salt, 1/4 teaspoon chilli powder', 'Cheese straws', 2, '2');
INSERT INTO RECIPE (ID, DESCRIPTION, IMG, INGREDIENTS, NAME, RATING, RATINGS) VALUES (5, 'Combine all of the ingredients together and mix well.Cook in the oven for 45 mins-1 hr until the chicken is cooked through and golden. Serve with salad, if you like.', 'http://www.reciperoulette.tv/public/upload/ac018de74960be035c3fdbaee5af4118.jpg', 'juice of 3 limes, 1 red onion, chopped, 1 tomato, chopped, 4 tablespoons olive oil, 1 tablespoon white vinegar, 1 small red chilli, seeded and minced, 3 tablespoons chopped fresh coriander, juice of 1/2 orange, salt and pepper', 'Harissa chicken', 3, '3');
INSERT INTO RECIPE (ID, DESCRIPTION, IMG, INGREDIENTS, NAME, RATING, RATINGS) VALUES (6, 'Mix the olive oil, salt, pepper, red wine vinegar, honey, Italian herbs, fresh mint and parsley in a bowl; pour over the salad. Crumble feta on top and serve!', 'http://www.reciperoulette.tv/public/upload/875ecc1757e2629ef3f1d97424a5aaae.jpg', '2 tablespoons red wine vinegar, 1 teaspoon honey, 1 teaspoon Italian herbs, 2 teaspoons finely chopped fresh mint, 2 teaspoons finely chopped parsley, 150g feta cheese', 'Greek salad', 5, '5');
INSERT INTO RECIPE (ID, DESCRIPTION, IMG, INGREDIENTS, NAME, RATING, RATINGS) VALUES (7, 'Pour apple juice into a large deep pot, and simmer for 20 minutes. Add water, lemon juice, rum, honey, ginger, cinnamon and lemon slices.', 'http://www.reciperoulette.tv/public/assets/images/food.jpg', '4 litres pure apple juice, 2 litres water, 12 lemons, juiced, 2/3 bottle good rum (Malibu works great), 3 tablespoons honey, 2 thumb-sized pieces root ginger, chopped, 1 cinnamon stick, 1 lemon, sliced', 'Lemonade', 1, '1');


